### PR TITLE
[DOCS-7370] Add Alfresco Sync Service 3.11 docs

### PR DESCRIPTION
**Pull request by anxumalo**
This PR incorporates updates for the next release of Alfresco Sync Sync. See the individual commits for more details.

### CODE REVIEW

**Review by abhishekkumar31 — APPROVED** [review]
LGTM

**Comment by isandhu** [comment]
I think it all looks correct.

**Review by isandhu — APPROVED** [review]
All good.

**Review by oliveralfresco2018 — APPROVED** [review]
LGTM

**Review by PiplaniVinay — APPROVED** [review]
LGTM

**Pull request merged**
