### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by OpenPj**
Updated the compatibility matrix for the transform service

### CODE REVIEW

**Comment by anxumalo** [comment]
Hi @OpenPj Thank you for the suggested update for the Alfresco product documentation.

I'm curious about why you'd like to update this page - was there something specific you were looking for? 

- The Supported platforms page (`transform-service/latest/support/index.md`) gives the compatibility for the latest release - which is currently *Alfresco Transform Service (ATS) 3.0*. 
- You can find the compatibility for previous ATS releases by changing the version dropdown next to the product name. 
- Alternatively, you can check the compatible integrations & apps with Alfresco Content Services in https://docs.alfresco.com/content-services/latest/support/.

**Comment by anxumalo** [comment]
Closing PR since Alfresco Transform Service (ATS) 3.0 is only compatible with Alfresco Content Services 7.4. Please see my previous comment for more details.

**Comment by OpenPj** [comment]
This page contains wrong information because the Alfresco Transform Service is compatible and supported for ACS 7.x

**Comment by anxumalo** [comment]
@OpenPj The best place to find the supported ATS versions is in each individual ACS Supported platforms page, where we specify the versions that are compatible with each ACS versions based on our QA activities. Please review the following pages to find this information:

- https://docs.alfresco.com/content-services/latest/support/ (currently ACS 7.4)
- https://docs.alfresco.com/content-services/7.3/support/ 
- https://docs.alfresco.com/content-services/7.2/support/ 
- https://docs.alfresco.com/content-services/7.1/support/

**Please note: Alfresco Transform Service 4.x doesn't exist, so there will be no documentation for that version.** 

As mentioned before, this Supported platforms page (`transform-service/latest/support/index.md`) gives the compatibility for the **latest** release of the Transform Service - which is currently ATS 3.0.

The all-in-one Transform Core Engine Spring Boot app `alfresco-transform-core-aio-boot-4.0.x.jar` is one of the **ATS 3.0 components**. The version of the Spring Boot app differs from the ATS release version, but the ATS release version matches the Transform Router version. You can also verify the released versions in the `acs-deployment` project:

- https://github.com/Alfresco/acs-deployment/blob/master/docker-compose/7.4.N-docker-compose.yml#L61
- https://github.com/Alfresco/acs-deployment/blob/master/docker-compose/7.4.N-docker-compose.yml#L75

**Pull request closed without merging**
