### PR TITLE
[DOCS-6984] Update Support Handbook - Support Case Life Cycle page

### PR DESCRIPTION
**Pull request by anxumalo**

### CODE REVIEW

**Comment by anxumalo** [comment]
> Looks good!

Thanks @kbecker9 - I've added a few minor fixes to the terminology so this is ready for a final review

**Comment by kbecker9** [comment]
No changes needed, looks good!

**Comment by Amy-Hyland** [comment]
I've reviewed the changes, they look good. I noticed the Introduction page could be updated, once these changes are made, to reflect the revision date: "Support Handbook updated as of September 3, 2021, and revisions effective on November 3, 2021."

**Review by Amy-Hyland — APPROVED** [review]

**Comment by anxumalo** [comment]
Thanks @Amy-Hyland - I'll verify the dates with Support and fix it in the next ticket for the Support Handbook

**Pull request merged**
