### PR TITLE
[DOCS-6906] Add collaborators column

### PR DESCRIPTION
**Pull request by oliveralfresco2018**

### CODE REVIEW

**Review by Artur-Piechuta — APPROVED** [review]
LGTM

**Review by Amy-Hyland — CHANGES_REQUESTED** [review]
The generated page upon building doesn't look easy to read, It seems like it should be a table with columns, but is a scrollable code block. I could be wrong, but I'll show you what I see: 
image I edited the file with corrections intending to suggest changes, and it removed the previous review.

**Comment by oliveralfresco2018** [comment]
@Amy-Hyland thanks for the review

This is the only change for this PR.

Collaborators | Displays an icon for each of the collaborators that are collaborating on a project, for more see Collaborators.

I'm not sure what you're talking about. 

Can you re-review and give me a shout if theres something else you want to discuss and you can share screen !    :-) !!

**Review by gravitonian — APPROVED** [review]
LGTM

**Pull request merged**
