### PR TITLE
[DOCS-7306] Add Outlook Integration 2.10 compatibility with ACS 7.4

### PR DESCRIPTION
**Pull request by anxumalo**

### CODE REVIEW

**Comment by anxumalo** [comment]
Hi @timblochwitz - this PR is now ready for your review for the upcoming release. Thanks

**Comment by timblochwitz** [comment]
@anxumalo LGTM. Can be merged. Thank you!

**Comment by Dougiefresh4ever** [comment]
Bad with this stuff can u just do stuff to get my stuff working right

**Review by ariadnags — APPROVED** [review]
LGTM

**Comment by Dougiefresh4ever** [comment]
What was this ?

**Pull request merged**
