### PR TITLE
[DOCS-6830] SAML Module 1.2.3 added

### PR DESCRIPTION
**Pull request by Amy-Hyland**
SAML Module 1.2.3 added new SAML version to content services, and SAML listed as supported for ACS 7.1 and 7.2.

### CODE REVIEW

**Review by dsibilio — APPROVED** [review]

**Review by anxumalo — COMMENTED** [review]
@Amy-Hyland Please add SAML 1.2.3 in `content-services/7.1/support/index.md`

**Comment by Amy-Hyland** [comment]
I've updated the changes in this commit https://github.com/Alfresco/docs-alfresco/pull/741/commits/4cf076c158d1c6b9df83291d153cc157988a5274

**Review by oliveralfresco2018 — APPROVED** [review]
LGTM built ok.

**Comment by anxumalo** [comment]
> @Amy-Hyland Please add SAML 1.2.3 in `content-services/7.1/support/index.md`

Sorry, I got this one wrong! I've now corrected the entries in the latest commit. This adds compatibility for ACS 7.2.1 only. See more details in DOCS-6830.

**Review by anxumalo — APPROVED** [review]
LGTM

**Pull request merged**
