### PR TITLE
[DOCS-6941] Updates for Alfresco Content Connector for AWS S3 5.1

### PR DESCRIPTION
**Pull request by Amy-Hyland**
Updates for ACS 7.3 compatibility and Java 17 support.

### CODE REVIEW

**Review by anxumalo — CHANGES_REQUESTED** [review]
Looks great @Amy-Hyland - just a few minor improvements

**Review by HeinRagas — APPROVED** [review]
Looks good. Thank you for your hard work!

**Comment by Amy-Hyland** [comment]
I've updated the title and included the suggested change.

**Review by anxumalo — APPROVED** [review]
LGTM 👍🏼

**Pull request merged**
