### PR TITLE
[DOCS-6928] Extension Inspector 1.5 version bump

### PR DESCRIPTION
**Pull request by Amy-Hyland**
Updated to new version 1.5 and removed trailing spaces

### CODE REVIEW

**Comment by anxumalo** [comment]
@HeinRagas This PR is ready for review

**Review by HeinRagas — APPROVED** [review]
I'm not sure I am the right person to review this, but it looks good to me

**Review by anxumalo — COMMENTED** [review]
Let's update the ACS version in the example usage from `7.2.0` to `7.3.0` (line 120). Otherwise LGTM

**Review by anxumalo — APPROVED** [review]
LGTM 👍🏼

**Pull request merged**
