### PR TITLE
[DOCS-6846] Update notes for enterprise users who install ACS with zip

### PR DESCRIPTION
**Pull request by abhinavmishra14**
Added additional lines to indicate users to install the required binaries on transform service layer in order for transform service to be fully functional. I have been getting feedback that this part of the notes doesn't mention this important detail and users are confused with the setps.

### CODE REVIEW

**Comment by anxumalo** [comment]
Thank you for your feedback on the Alfresco documentation. We really appreciate the time that you have taken to let us know what you think.

We have taken note of your recommended fix and will validate the change with our Engineering team.

**Comment by anxumalo** [comment]
This is tracked internally in DOCS-6846

**Review by aborroy — APPROVED** [review]
LGTM

**Review by anxumalo — APPROVED** [review]
LGTM. Thanks @abhinavmishra14 for the updates

**Pull request merged**
