### PR TITLE
[DOCS-7030] Alfresco Content Services 7.3 Enterprise Trial updates

### PR DESCRIPTION
**Pull request by Amy-Hyland**
- Added new properties in tables for Content App and Control Center.
- Updated image versions.

### CODE REVIEW

**Review by HeinRagas — DISMISSED** [review]
Thank you for your hard work!

**Review by anxumalo — CHANGES_REQUESTED** [review]
Looks great - just a minor search/replace fix needed based on line 21:

> For example, you can create a folder `acs-trial`.

Unless your output differs to mine, it might be better to change all the new examples to use this folder name (i.e. write `acs-trial` instead of `acstrial`) otherwise it could be confusing if both versions are documented.

**Comment by Amy-Hyland** [comment]
I've updated the "acstrial" to "acs-trial", and removed the "%" from one of the commands.

**Review by anxumalo — APPROVED** [review]
LGTM 👍🏼

**Pull request merged**
