### PR TITLE
[DOCS-6920] Update ACS Supported Platforms pages

### PR DESCRIPTION
**Pull request by anxumalo**

### CODE REVIEW

**Review by Amy-Hyland — APPROVED** [review]
For some reason, the left column is narrower on the 7.0 page, but otherwise LGTM.

image

**Comment by anxumalo** [comment]
Thanks for the review @Amy-Hyland.

I noticed the same thing - the column widths are not configurable - they adjust based on the browser width and column content.

**Review by vprovaggi — COMMENTED** [review]
Remove Microsoft IE 11 support from the platform. We now support just Edge

**Comment by anxumalo** [comment]
> Remove Microsoft IE 11 support from the platform. We now support just Edge

As discussed, we can consider this update in the next release. We already list Microsoft Edge as a supported browser.

**Pull request merged**
