### PR TITLE
[DOCS-7294] Add ACS 23.1 Supported platforms page

### PR DESCRIPTION
**Pull request by anxumalo**

### CODE REVIEW

**Review by HeinRagas — APPROVED** [review]
*thumbs-up emoji*

**Review by oliveralfresco2018 — APPROVED** [review]
LGTM, see response in https://alfresco.atlassian.net/browse/DOCS-7401 about your Search related question

**Comment by jbrychcy** [comment]
LGTM :)

**Review by jbrychcy — COMMENTED** [review]
LGTM

**Pull request merged**
