### PR TITLE
[DOCS-7009] Add new Search feature for Mac & Windows

### PR DESCRIPTION
**Pull request by anxumalo**

### CODE REVIEW

**Review by abhishekkumar31 — COMMENTED** [review]
_desktop-sync/images/ds-system-menu-1.14.png_ seems a little blurry. Can we use more sharp image @anxumalo  ? The team can provide it in case you need it from us.

**Comment by anxumalo** [comment]
> _desktop-sync/images/ds-system-menu-1.14.png_ seems a little blurry. Can we use more sharp image @anxumalo ? The team can provide it in case you need it from us.

Sure - that'd be great! I've requested a better version via the team channel

**Comment by anxumalo** [comment]
Hi @abhishekkumar31, I've now updated the image so please review & approve the changes. cc. @lilustig Thanks

**Review by abhishekkumar31 — APPROVED** [review]
LGTM

**Pull request merged**
