### PR TITLE
[DOCS-6653] - Process page updates

### PR DESCRIPTION
**Pull request by oliveralfresco2018**

### CODE REVIEW

**Review by Artur-Piechuta — COMMENTED** [review]
Could you describe another way of starting a new process? It is by pressing "Start process" button. The difference is the there is no file attached automatically in this case.

**Review by Artur-Piechuta — DISMISSED** [review]
LGTM

**Review by anxumalo — COMMENTED** [review]
Looks good - see inline comments

**Review by gravitonian — APPROVED** [review]
LGTM

**Pull request merged**
