### PR TITLE
[DOCS-7433] Update ACA 3.6 compatibility with ACS and configuration

### PR DESCRIPTION
**Pull request by Prosune**
This pull request includes three commits. Two commits for the Support page and one commit is related to the DOCS-7124 task (related to "Update Content Accelerator install configurations for Install guide."

### CODE REVIEW

**Review by anxumalo — COMMENTED** [review]
Hi @Prosune - sending early feedback on the ACS compatibility update. 
Each of the `content-services/7.x/support/index.md` files provide two versions of ACS. For example, ACS 7.4.1 and 7.4.0. Please make sure you add the new release version to both tables. Hope this helps! 
cc. @aritrihore - the same advice will apply when you work on the ACS compatibility with AEV.

**Comment by Prosune** [comment]
@dpatel-alfresco Please review changes for DOCS-7124

**Comment by Prosune** [comment]
> Hi @Prosune - sending early feedback on the ACS compatibility update. Each of the `content-services/7.x/support/index.md` files provide two versions of ACS. For example, ACS 7.4.1 and 7.4.0. Please make sure you add the new release version to both tables. Hope this helps! cc. @aritrihore - the same advice will apply when you work on the ACS compatibility with AEV.

@anxumalo Thanks for your feedback. Pushed the suggested changes.

**Review by dpatel-alfresco — APPROVED** [review]
Looks good to me.

**Review by anxumalo — APPROVED** [review]

**Pull request merged**
