### PR TITLE
[DOCS-6249] Add SAP Cloud Connector 1.1 docs

### PR DESCRIPTION
**Pull request by anxumalo**
This branch will be merged to `master` once the release has been approved for GA release

### CODE REVIEW

**Review by gravitonian — DISMISSED** [review]
Looked through 1.1 pages and tested links. Looks good.
Browsed through also version 1.0.

**Review by oliveralfresco2018 — DISMISSED** [review]
merge approval

**Review by gravitonian — APPROVED** [review]
Merge approve

**Review by oliveralfresco2018 — APPROVED** [review]
lgtm

**Pull request merged**
